### PR TITLE
Only use short-circuiting operators in VB.NET.

### PR DESCRIPTION
**Pull request by Corniel**
Only use short-circuiting operators, as further analyzing the expression will not change the outcome. It is a typical VB.NET issue, as the none short-circuiting keywords are the default onces.

### CODE REVIEW

**Comment by Corniel** [comment]
Hmm, I'm still inexpericenced with Github. This pull request was of course intended for   SonarSource-VisualStudio/sonaranalyzer-dotnet,

**Comment by ghost** [comment]
@Corniel This rule reports on all usages of non short-circuiting `And` and `Or` operators. ~~I think banning the usage of these operators is not a good idea, and can't be a general suggestion. There are valid usages of these operators when you consider boolean expressions with side-effects that must be executed.~~ (These valid usages can be overcome by assigning the result of the expression to a local variable, thus executing the side effect.)

I just checked our rule repository and found this rule. https://jira.sonarsource.com/browse/RSPEC-2178. Could you move this PR to the https://github.com/SonarSource-VisualStudio/sonaranalyzer-dotnet. We'll have to rework it a bit, because we probably will add it for C# too. But in C# we need to check if the operator is `bool.operator|` or `bool.operator&`.

**Comment by Corniel** [comment]
I forgot to take the bitwise into account, I will add it. As far as I know, it is not possible to do this in C#.

**Comment by ghost** [comment]
@Corniel Yes it is possible. See it here: https://dotnetfiddle.net/TRzjMY

```
var t = true;
var f = false;
Console.WriteLine(t | f);
Console.WriteLine(t & f);

Console.WriteLine(t || f);
Console.WriteLine(t && f);

// but shouldn't trigger on int:
var i = 1 << 1; //10
var j = 1 << 4; //10000
Console.WriteLine(i | j); // Prints 10010 == 18
Console.WriteLine(i & j); // Prints 0
```

But don't worry about the C# implementation. I'll add that myself.

**Comment by Corniel** [comment]
Never tried it. But you are right.

**Comment by ghost** [comment]
The matching PR was merged to master in https://github.com/SonarSource-VisualStudio/sonaranalyzer-dotnet/commit/07cbb90c3e2acf03dc6192f463f8994bda251eb8.

**Pull request closed without merging**
